Job_Portal/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Jop_Portal.Data;
using Jop_Portal.Models;
using Microsoft.AspNetCore.Identity;

namespace Jop_Portal.Controllers
{
    public class AccountsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly UserManager<IdentityUser> _userManager;

        public AccountsController(ApplicationDbContext context, IWebHostEnvironment hostingEnvironment, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
            _userManager = userManager;
        }


        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Account == null)
            {
                return NotFound();
            }
            var offers= _context.Offers.Where(o => (o.Active &&o.UserId==id)).OrderByDescending(o=>o.CreatedAt);
            var account =  _context.Account
                .SingleOrDefault(m => m.Id == id);
            var user = _context.Users.SingleOrDefault(u=>u.Id == id);
            ViewData["Name"] = account.Name;
            ViewData["Photo"] = account.Photo;
            ViewData["About"] = account.About;
            ViewData["UserId"] =account.Id;
            ViewData["Phone"] = user.PhoneNumber;
            ViewData["Email"] = user.Email;
            ViewData["Id"] = _userManager.GetUserId(User);
            return View(offers);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IdentityUser user, string name, IFormFile photo,string?About)
        {
            Account account = new Account();
            if (photo != null && photo.Length > 0)
            {
                // Get the wwwroot path
                string uploadPath = Path.Combine(_hostingEnvironment.WebRootPath, "imj");
                Directory.CreateDirectory(uploadPath);

                // Generate a unique filename for the uploaded file
                string newfilename = $"{Guid.NewGuid().ToString()}{Path.GetExtension(photo.FileName)}";
                string fileName = Path.Combine(uploadPath, newfilename);

                // Save the file to the server
                using (var fileStream = new FileStream(fileName, FileMode.Create))
                {
                    photo.CopyTo(fileStream);
                }
                account.Photo = $"/imj/{newfilename}";
            }
            else
                account.Photo = "/imj/default.jpg";
            // Optionally, save the file path to a database or return it to the user
            account.Id = user.Id;
            account.Name = name;
            account.Reports =0;
            account.About =About;
            if (ModelState.IsValid)
            {
                _context.Add(account);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(account);
        }

       
       
    }
}

Job_Portal/Controllers/OffersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Jop_Portal.Data;
using Jop_Portal.Models;
using Microsoft.AspNetCore.Identity;

namespace Jop_Portal.Controllers
{
    public class OffersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public OffersController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Offers
        public async Task<IActionResult> Index(string id)
        {
            var applicationDbContext = _context.Offers.Where(o => o.UserId==id);
            return View(applicationDbContext.ToList());
        }

    
        // GET: Offers/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Offers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,JobTittle,Photo,Description,Available,Active,CreatedAt,UserId")] Offers offers)
        {
                
                var file = HttpContext.Request.Form.Files;
                    string imageName = Guid.NewGuid().ToString() + Path.GetExtension(file[0].FileName);
                    var filePath = Path.Combine("wwwroot", "imj", imageName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        file[0].CopyTo(fileStream); // Save in the Images folder
                    }

                offers.Photo = $"/imj/{imageName}"; // Save in the database
                offers.Active = false;
                offers.CreatedAt = DateTime.Now;
                offers.UserId = _userManager.GetUserId(User);
                var user = _context.Account.SingleOrDefault(a => a.Id == offers.UserId);
                offers.UserName = user.Name;
                offers.UserPhoto = user.Photo;
                 _context.Add(offers);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { id = _userManager.GetUserId(User) });
        }
        // GET: Offers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Offers == null)
            {
                return NotFound();
            }

            var offers = await _context.Offers
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (offers == null)
            {
                return NotFound();
            }

            return View(offers);
        }

        // POST: Offers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Offers == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Offers'  is null.");
            }
            var offers = await _context.Offers.FindAsync(id);
            if (offers != null)
            {
                _context.Offers.Remove(offers);
            }
            
            await _context.SaveChangesAsync();
            if (User==null || User.IsInRole("Admin"))
                return RedirectToAction("Index", "Admin");
            return RedirectToAction(nameof(Index), new { id = _userManager.GetUserId(User) });
        }

        private bool OffersExists(int id)
        {
          return (_context.Offers?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Job_Portal/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Jop_Portal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Jop_Portal.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" style="background-color:#3097D1">
            <div class="container-fluid">
                @if (User.IsInRole("Admin"))
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index">Job_Portal</a>
                            </li>
                            <li class="nav-item">
                             <a class="nav-link text-light" asp-area="" asp-controller="Admin" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                </form>
                            </li>
                    </ul>
                   
                    </div>
                }
                else{
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Job_Portal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Accounts" asp-action="Details" asp-route-id="@UserManager.GetUserId(User)" title="Manage">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Offers" asp-action="Create" asp-route-id="@UserManager.GetUserId(User)" title="Manage">Create offer</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
                 }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>